# CUSTOMER SERVICE DATA PREPROCESSING

## Import Relevant Libraries

In [1]:
import pandas as pd

## Loading the Raw Data

In [2]:
raw_csv_data = pd.read_csv("customer_service_resolution_rawdata.csv")

In [3]:
raw_csv_data.head()

,Customer_ID,Service_Type_Code,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1038,6,23/12/2024,277,4,58,165,72,1,1,3,2.0
1,1028,21,14/11/2023,115,34,31,286,44,1,1,2,2.5
2,1014,6,01/02/2023,384,48,47,222,96,2,0,2,5.5
3,1042,26,31/10/2024,467,18,58,315,67,2,1,0,5.5
4,1007,12,12/10/2023,469,40,21,352,53,1,3,3,7.0

In [4]:
data=raw_csv_data.copy()

In [5]:
data.head()

,Customer_ID,Service_Type_Code,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1038,6,23/12/2024,277,4,58,165,72,1,1,3,2.0
1,1028,21,14/11/2023,115,34,31,286,44,1,1,2,2.5
2,1014,6,01/02/2023,384,48,47,222,96,2,0,2,5.5
3,1042,26,31/10/2024,467,18,58,315,67,2,1,0,5.5
4,1007,12,12/10/2023,469,40,21,352,53,1,3,3,7.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  700 non-null    int64
 1   Service_Type_Code            700 non-null    int64
 2   Request_Date                 700 non-null    object
 3   Service_Cost                 700 non-null    int64
 4   Distance_to_Service_Center   700 non-null    int64
 5   Customer_Age                 700 non-null    int64
 6   Daily_Request_Volume_Avg     700 non-null    int64
 7   Customer_Satisfaction_Index  700 non-null    int64
 8   Customer_Tier                700 non-null    int64
 9   Previous_Requests            700 non-null    int64
 10  Support_Contacts             700 non-null    int64
 11  Issue_Resolution_Time_Hours  700 non-null    float64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB

In [7]:
data=data.drop(['Customer_ID'], axis = 1)

In [8]:
data['Service_Type_Code'].unique()

array([ 6, 21, 26, 12, 13, 29, 15, 16, 22, 11, 28,  5,  4,  3, 19, 20, 25,
       18,  9, 17, 14,  1, 23, 10,  8, 24, 27,  2,  7], dtype=int64)

In [9]:
data['Service_Type_Code'].min()

1

In [10]:
data['Service_Type_Code'].max()

29

In [11]:
sorted(data['Service_Type_Code'].unique())

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

## Getting dummies for the Service_Type_Code

In [12]:
service_columns = pd.get_dummies(data['Service_Type_Code'])

In [13]:
service_columns

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,26,27,28,29
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [14]:
service_columns['check'] = service_columns.sum(axis=1)
service_columns

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,check
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
697,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [15]:
service_columns['check'].sum()

700

In [16]:
service_columns = service_columns.drop(['check'], axis = 1)
service_columns

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,26,27,28,29
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
696,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
697,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
698,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

# Group the Service Type Codes:

In [17]:
data.columns.values

array(['Service_Type_Code', 'Request_Date', 'Service_Cost',
       'Distance_to_Service_Center', 'Customer_Age',
       'Daily_Request_Volume_Avg', 'Customer_Satisfaction_Index',
       'Customer_Tier', 'Previous_Requests', 'Support_Contacts',
       'Issue_Resolution_Time_Hours'], dtype=object)

In [18]:
service_columns.columns.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=object)

In [19]:
data = data.drop(['Service_Type_Code'], axis = 1)

In [20]:
data.head()

,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,23/12/2024,277,4,58,165,72,1,1,3,2.0
1,14/11/2023,115,34,31,286,44,1,1,2,2.5
2,01/02/2023,384,48,47,222,96,2,0,2,5.5
3,31/10/2024,467,18,58,315,67,2,1,0,5.5
4,12/10/2023,469,40,21,352,53,1,3,3,7.0

In [21]:
service_type_1 = service_columns.loc[:, 1:8].max(axis=1)
service_type_2 = service_columns.loc[:, 9:15].max(axis=1)
service_type_3 = service_columns.loc[:, 16:23].max(axis=1)
service_type_4 = service_columns.loc[:, 24:].max(axis=1)

In [22]:
#Concatenate Column Values
data = pd.concat([data, service_type_1, service_type_2, service_type_3, service_type_4], axis = 1)
data.head()

,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours,0,1,2,3
0,23/12/2024,277,4,58,165,72,1,1,3,2.0,1,0,0,0
1,14/11/2023,115,34,31,286,44,1,1,2,2.5,0,0,1,0
2,01/02/2023,384,48,47,222,96,2,0,2,5.5,1,0,0,0
3,31/10/2024,467,18,58,315,67,2,1,0,5.5,0,0,0,1
4,12/10/2023,469,40,21,352,53,1,3,3,7.0,0,1,0,0

In [23]:
data.columns.values

array(['Request_Date', 'Service_Cost', 'Distance_to_Service_Center',
       'Customer_Age', 'Daily_Request_Volume_Avg',
       'Customer_Satisfaction_Index', 'Customer_Tier',
       'Previous_Requests', 'Support_Contacts',
       'Issue_Resolution_Time_Hours', 0, 1, 2, 3], dtype=object)

In [24]:
column_names=['Request_Date', 'Service_Cost', 'Distance_to_Service_Center',
       'Customer_Age', 'Daily_Request_Volume_Avg',
       'Customer_Satisfaction_Index', 'Customer_Tier',
       'Previous_Requests', 'Support_Contacts',
       'Issue_Resolution_Time_Hours','service_type_1', 'service_type_2', 'service_type_3', 'service_type_4']

In [25]:
data.columns = column_names

In [26]:
data.head()

,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours,service_type_1,service_type_2,service_type_3,service_type_4
0,23/12/2024,277,4,58,165,72,1,1,3,2.0,1,0,0,0
1,14/11/2023,115,34,31,286,44,1,1,2,2.5,0,0,1,0
2,01/02/2023,384,48,47,222,96,2,0,2,5.5,1,0,0,0
3,31/10/2024,467,18,58,315,67,2,1,0,5.5,0,0,0,1
4,12/10/2023,469,40,21,352,53,1,3,3,7.0,0,1,0,0

In [27]:
data.columns

Index(['Request_Date', 'Service_Cost', 'Distance_to_Service_Center',
       'Customer_Age', 'Daily_Request_Volume_Avg',
       'Customer_Satisfaction_Index', 'Customer_Tier', 'Previous_Requests',
       'Support_Contacts', 'Issue_Resolution_Time_Hours', 'service_type_1',
       'service_type_2', 'service_type_3', 'service_type_4'],
      dtype='object')

In [28]:
column_names_reordered=['service_type_1',
       'service_type_2', 'service_type_3', 'service_type_4', 'Request_Date', 'Service_Cost', 'Distance_to_Service_Center',
       'Customer_Age', 'Daily_Request_Volume_Avg',
       'Customer_Satisfaction_Index', 'Customer_Tier', 'Previous_Requests',
       'Support_Contacts', 'Issue_Resolution_Time_Hours']

In [29]:
data = data[column_names_reordered]

In [30]:
data.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1,0,0,0,23/12/2024,277,4,58,165,72,1,1,3,2.0
1,0,0,1,0,14/11/2023,115,34,31,286,44,1,1,2,2.5
2,1,0,0,0,01/02/2023,384,48,47,222,96,2,0,2,5.5
3,0,0,0,1,31/10/2024,467,18,58,315,67,2,1,0,5.5
4,0,1,0,0,12/10/2023,469,40,21,352,53,1,3,3,7.0

In [31]:
data_service_mod = data.copy()

In [32]:
data_service_mod.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1,0,0,0,23/12/2024,277,4,58,165,72,1,1,3,2.0
1,0,0,1,0,14/11/2023,115,34,31,286,44,1,1,2,2.5
2,1,0,0,0,01/02/2023,384,48,47,222,96,2,0,2,5.5
3,0,0,0,1,31/10/2024,467,18,58,315,67,2,1,0,5.5
4,0,1,0,0,12/10/2023,469,40,21,352,53,1,3,3,7.0

In [33]:
# Working on the Request_Date column

In [34]:
type(data_service_mod['Request_Date'][0])

str

In [35]:
data_service_mod['Request_Date'] = pd.to_datetime(data_service_mod['Request_Date'], format = '%d/%m/%Y')

In [36]:
type(data_service_mod['Request_Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [37]:
data_service_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   service_type_1               700 non-null    uint8
 1   service_type_2               700 non-null    uint8
 2   service_type_3               700 non-null    uint8
 3   service_type_4               700 non-null    uint8
 4   Request_Date                 700 non-null    datetime64[ns]
 5   Service_Cost                 700 non-null    int64
 6   Distance_to_Service_Center   700 non-null    int64
 7   Customer_Age                 700 non-null    int64
 8   Daily_Request_Volume_Avg     700 non-null    int64
 9   Customer_Satisfaction_Index  700 non-null    int64
 10  Customer_Tier                700 non-null    int64
 11  Previous_Requests            700 non-null    int64
 12  Support_Contacts             700 non-null    int64
 13  Issue_Resolution_Time_Hours  700 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(8), uint8(4)
memory usage: 57.5 KB

In [38]:
data_service_mod['Request_Date'][0].month

12

In [39]:
list_months = []
list_months

[]

In [40]:
data_service_mod.shape

(700, 14)

In [41]:
for i in range(data_service_mod.shape[0]):
    list_months.append(data_service_mod['Request_Date'][i].month)

In [42]:
len(list_months)

700

In [43]:
data_service_mod['Month Value'] = list_months

In [44]:
data_service_mod.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours,Month Value
0,1,0,0,0,2024-12-23,277,4,58,165,72,1,1,3,2.0,12
1,0,0,1,0,2023-11-14,115,34,31,286,44,1,1,2,2.5,11
2,1,0,0,0,2023-02-01,384,48,47,222,96,2,0,2,5.5,2
3,0,0,0,1,2024-10-31,467,18,58,315,67,2,1,0,5.5,10
4,0,1,0,0,2023-10-12,469,40,21,352,53,1,3,3,7.0,10

In [45]:
# Extracting the day of the week

In [46]:
data_service_mod['Request_Date'][699].weekday()

6

In [47]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [48]:
data_service_mod['Day of the Week'] = data_service_mod['Request_Date'].apply(date_to_weekday)

In [49]:
data_service_mod.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Request_Date,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours,Month Value,Day of the Week
0,1,0,0,0,2024-12-23,277,4,58,165,72,1,1,3,2.0,12,0
1,0,0,1,0,2023-11-14,115,34,31,286,44,1,1,2,2.5,11,1
2,1,0,0,0,2023-02-01,384,48,47,222,96,2,0,2,5.5,2,2
3,0,0,0,1,2024-10-31,467,18,58,315,67,2,1,0,5.5,10,3
4,0,1,0,0,2023-10-12,469,40,21,352,53,1,3,3,7.0,10,3

In [50]:
data_service_mod = data_service_mod.drop(['Request_Date'], axis = 1)
data_service_mod.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours,Month Value,Day of the Week
0,1,0,0,0,277,4,58,165,72,1,1,3,2.0,12,0
1,0,0,1,0,115,34,31,286,44,1,1,2,2.5,11,1
2,1,0,0,0,384,48,47,222,96,2,0,2,5.5,2,2
3,0,0,0,1,467,18,58,315,67,2,1,0,5.5,10,3
4,0,1,0,0,469,40,21,352,53,1,3,3,7.0,10,3

In [51]:
data_service_mod.columns

Index(['service_type_1', 'service_type_2', 'service_type_3', 'service_type_4',
       'Service_Cost', 'Distance_to_Service_Center', 'Customer_Age',
       'Daily_Request_Volume_Avg', 'Customer_Satisfaction_Index',
       'Customer_Tier', 'Previous_Requests', 'Support_Contacts',
       'Issue_Resolution_Time_Hours', 'Month Value', 'Day of the Week'],
      dtype='object')

In [52]:
column_names_upd=['service_type_1', 'service_type_2', 'service_type_3', 'service_type_4', 'Month Value', 'Day of the Week',
       'Service_Cost', 'Distance_to_Service_Center', 'Customer_Age',
       'Daily_Request_Volume_Avg', 'Customer_Satisfaction_Index',
       'Customer_Tier', 'Previous_Requests', 'Support_Contacts',
       'Issue_Resolution_Time_Hours']

In [53]:
data_service_mod = data_service_mod[column_names_upd]
data_service_mod.head()

,service_type_1,service_type_2,service_type_3,service_type_4,Month Value,Day of the Week,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1,0,0,0,12,0,277,4,58,165,72,1,1,3,2.0
1,0,0,1,0,11,1,115,34,31,286,44,1,1,2,2.5
2,1,0,0,0,2,2,384,48,47,222,96,2,0,2,5.5
3,0,0,0,1,10,3,467,18,58,315,67,2,1,0,5.5
4,0,1,0,0,10,3,469,40,21,352,53,1,3,3,7.0

In [54]:
data_preprocessed = data_service_mod.copy()
data_preprocessed.head(10)

,service_type_1,service_type_2,service_type_3,service_type_4,Month Value,Day of the Week,Service_Cost,Distance_to_Service_Center,Customer_Age,Daily_Request_Volume_Avg,Customer_Satisfaction_Index,Customer_Tier,Previous_Requests,Support_Contacts,Issue_Resolution_Time_Hours
0,1,0,0,0,12,0,277,4,58,165,72,1,1,3,2.0
1,0,0,1,0,11,1,115,34,31,286,44,1,1,2,2.5
2,1,0,0,0,2,2,384,48,47,222,96,2,0,2,5.5
3,0,0,0,1,10,3,467,18,58,315,67,2,1,0,5.5
4,0,1,0,0,10,3,469,40,21,352,53,1,3,3,7.0
5,0,1,0,0,11,2,311,35,21,203,44,2,0,0,4.0
6,0,1,0,0,3,0,344,41,45,333,93,1,3,2,5.5
7,0,0,0,1,4,6,475,29,25,363,95,2,1,0,5.5
8,0,1,0,0,10,4,292,29,19,374,98,3,0,3,5.0
9,0,0,1,0,5,2,420,38,58,249,72,2,1,2,8.0

In [55]:
data_preprocessed.to_csv('data_preprocessed.csv', index=False)